#!/usr/bin/env bash
# configuring Nginx so that it is redirecting to another page.

# Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i '/server_name _;/a \	location /redirect_me {\n	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n	}' /etc/nginx/sites-avilable/default
sudo service nginx restart
